# Cross-origin resource sharing related settings.
cors:
  # Allowed origins. Add one entry for each domain allowed to access the application.
  # Always include the protocol (http or https) and if not default for the
  # protocol, also the port number!
  origins:
    - http://localhost:9000/
    - http://localhost:9000

# Database settings
database:
    driver: pdo_mysql
    host:
    user:
    password:
    dbname:

# UiTID related settings.
uitid:
  test:
    consumer:
      key:
      secret:
    base_url: https://acc2.uitid.be/uitid/rest/
  live:
    consumer:
      key:
      secret:
    base_url: https://www.uitid.be/uitid/rest/

# debug settings
debug: false

# Rabbit MQ settings
rabbitmq:
  host:
  port:
  user:
  password:

# Insightly settings
insightly:
  host: https://api.insight.ly/v2.2
  api_key:
  project_config:
