subscribers:
    synchronous:
    asynchronous:
        CultuurNet\ProjectAanvraag\Project\Event\ProjectDeleted:
            - project_deleted_listener
        CultuurNet\ProjectAanvraag\Project\Event\ProjectBlocked:
            - project_blocked_listener
        CultuurNet\ProjectAanvraag\Project\Event\ProjectActivated:
            - project_activated_listener

listeners:
    project_activated_listener:
        class: \CultuurNet\ProjectAanvraag\Project\EventListener\ProjectActivatedEventListener
        arguments:
            - insightly_client
            - insightly.project_config

    project_deleted_listener:
        class: \CultuurNet\ProjectAanvraag\Project\EventListener\ProjectDeletedEventListener
        arguments:
            - insightly_client
            - insightly.project_config

    project_blocked_listener:
        class: \CultuurNet\ProjectAanvraag\Project\EventListener\ProjectBlockedEventListener
        arguments:
            - insightly_client
            - insightly.project_config

handlers:
    create_project_handler:
        command: CultuurNet\ProjectAanvraag\Project\Command\CreateProject
        class: \CultuurNet\ProjectAanvraag\Project\CommandHandler\CreateProjectCommandHandler
        arguments:
            - event_bus
            - orm.em
            - culturefeed_test
            - uitid_user_session_data_complete

    activate_project_handler:
        command: CultuurNet\ProjectAanvraag\Project\Command\ActivateProject
        class: \CultuurNet\ProjectAanvraag\Project\CommandHandler\ActivateProjectCommandHandler
        arguments:
          - event_bus
          - orm.em
          - culturefeed
          - uitid_user_session_data_complete

    request_activation_handler:
        command: CultuurNet\ProjectAanvraag\Project\Command\RequestActivationCommandHandler
        class: \CultuurNet\ProjectAanvraag\Project\CommandHandler\RequestActivationCommandHandler
        arguments:
          - event_bus
          - orm.em
          - uitid_user_session_data_complete
          - insightly_client

    delete_project_handler:
        command: CultuurNet\ProjectAanvraag\Project\Command\DeleteProject
        class: \CultuurNet\ProjectAanvraag\Project\CommandHandler\DeleteProjectCommandHandler
        arguments:
            - event_bus
            - orm.em
            - culturefeed
            - culturefeed_test
            - uitid_user_session_data_complete

    block_project_handler:
        command: CultuurNet\ProjectAanvraag\Project\Command\BlockProject
        class: \CultuurNet\ProjectAanvraag\Project\CommandHandler\BlockProjectCommandHandler
        arguments:
            - event_bus
            - orm.em
            - culturefeed
            - culturefeed_test
            - uitid_user_session_data_complete