subscribers:
    synchronous:
    asynchronous:
        CultuurNet\ProjectAanvraag\Project\Event\ProjectCreated:
            - project_created_listener
        CultuurNet\ProjectAanvraag\Project\Event\ProjectDeleted:
            - project_deleted_listener
        CultuurNet\ProjectAanvraag\Project\Event\ProjectBlocked:
            - project_blocked_listener
        CultuurNet\ProjectAanvraag\Project\Event\ProjectActivated:
            - project_activated_listener
        CultuurNet\ProjectAanvraag\Core\Event\QueueConsumers:
            - queue_consumers_listener
        CultuurNet\ProjectAanvraag\Core\Event\SyncConsumer:
            - sync_consumer_listener
        CultuurNet\ProjectAanvraag\Core\Event\QueueWidgetMigration:
            - queue_widget_migration_listener

listeners:
    project_created_listener:
        class: \CultuurNet\ProjectAanvraag\Project\EventListener\ProjectCreatedEventListener
        arguments:
            - insightly_client
            - insightly.project_config
            - orm.em

    project_activated_listener:
        class: \CultuurNet\ProjectAanvraag\Project\EventListener\ProjectActivatedEventListener
        arguments:
            - insightly_client
            - insightly.project_config

    project_deleted_listener:
        class: \CultuurNet\ProjectAanvraag\Project\EventListener\ProjectDeletedEventListener
        arguments:
            - insightly_client
            - insightly.project_config

    project_blocked_listener:
        class: \CultuurNet\ProjectAanvraag\Project\EventListener\ProjectBlockedEventListener
        arguments:
            - insightly_client
            - insightly.project_config

    queue_consumers_listener:
        class: \CultuurNet\ProjectAanvraag\Core\EventListener\QueueConsumersEventListener
        arguments:
            - culturefeed
            - culturefeed_test
            - event_bus

    sync_consumer_listener:
        class: \CultuurNet\ProjectAanvraag\Core\EventListener\SyncConsumerEventListener
        arguments:
            - project_repository
            - orm.em
            - insightly.project_config
    queue_widget_migration_listener:
        class: \CultuurNet\ProjectAanvraag\Core\EventListener\QueueWidgetMigrationEventListener
        arguments:
            - legacy_widgets_db
            - orm.em
            - project_repository
            - event_bus

handlers:
    create_project_handler:
        command: CultuurNet\ProjectAanvraag\Project\Command\CreateProject
        class: \CultuurNet\ProjectAanvraag\Project\CommandHandler\CreateProjectCommandHandler
        arguments:
            - event_bus
            - orm.em
            - culturefeed_test
            - culturefeed
            - uitid_user_session_data_complete

    activate_project_handler:
        command: CultuurNet\ProjectAanvraag\Project\Command\ActivateProject
        class: \CultuurNet\ProjectAanvraag\Project\CommandHandler\ActivateProjectCommandHandler
        arguments:
            - event_bus
            - orm.em
            - culturefeed
            - uitid_user_session_data_complete

    request_activation_handler:
        command: CultuurNet\ProjectAanvraag\Project\Command\RequestActivation
        class: \CultuurNet\ProjectAanvraag\Project\CommandHandler\RequestActivationCommandHandler
        arguments:
          - event_bus
          - orm.em
          - uitid_user_session_data_complete
          - insightly_client
          - insightly.project_config


    delete_project_handler:
        command: CultuurNet\ProjectAanvraag\Project\Command\DeleteProject
        class: \CultuurNet\ProjectAanvraag\Project\CommandHandler\DeleteProjectCommandHandler
        arguments:
            - event_bus
            - orm.em
            - culturefeed
            - culturefeed_test
            - uitid_user_session_data_complete

    block_project_handler:
        command: CultuurNet\ProjectAanvraag\Project\Command\BlockProject
        class: \CultuurNet\ProjectAanvraag\Project\CommandHandler\BlockProjectCommandHandler
        arguments:
            - event_bus
            - orm.em
            - culturefeed
            - culturefeed_test
            - uitid_user_session_data_complete

    update_widget_page_handler:
          command: CultuurNet\ProjectAanvraag\Widget\Command\UpdateWidgetPage
          class: \CultuurNet\ProjectAanvraag\Widget\CommandHandler\UpdateWidgetPageCommandHandler
          arguments:
              - event_bus
              - mongodbodm.dm
              - uitid_user_session_data_complete

    create_widget_page_handler:
              command: CultuurNet\ProjectAanvraag\Widget\Command\CreateWidgetPage
              class: \CultuurNet\ProjectAanvraag\Widget\CommandHandler\CreateWidgetPageCommandHandler
              arguments:
                  - event_bus
                  - mongodbodm.dm
                  - uitid_user_session_data_complete
                  - uuid_generator

    publish_widget_page_handler:
          command: CultuurNet\ProjectAanvraag\Widget\Command\PublishWidgetPage
          class: \CultuurNet\ProjectAanvraag\Widget\CommandHandler\PublishWidgetPageCommandHandler
          arguments:
              - event_bus
              - mongodbodm.dm
              - widget_repository
              - uitid_user_session_data_complete

    delete_widget_page_handler:
          command: CultuurNet\ProjectAanvraag\Widget\Command\DeleteWidgetPage
          class: \CultuurNet\ProjectAanvraag\Widget\CommandHandler\DeleteWidgetPageCommandHandler
          arguments:
              - event_bus
              - mongodbodm.dm
              - widget_repository
              - uitid_user_session_data_complete
